### PR TITLE
[NCL-6141] Use the callback headers and method info for callback

### PR DESCRIPTION
**Pull request by thescouser89**
### Checklist:

* [ ] Have you added a note in the CHANGELOG.md for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by thescouser89** [comment]
JENKINS DON'T YOU DISRESPECT ME WITH A BUILD FAILURE. HOW DARE YOU

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
WHO'S THE BOSS NOW JENKINS!? WHO!!!!!!!!!!

**Comment by thescouser89** [comment]
retest this please

**Review by janinko — APPROVED** [review]
YOU'RE THE BOSS, @thescouser89, OBVIOUSLY!!!!

**Pull request merged**
