### PR TITLE
[NCL-4937] Update to EAP 7.2.2 with JDK 11

### PR DESCRIPTION
**Pull request by michalovjan**
### Checklist:

* [ ] Have you added a note in the CHANGELOG.md for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by michalovjan** [comment]
retest this please

**Comment by michalovjan** [comment]
The test needs Maven that uses new JDK11 for it to run so Jenkins job needs to be updated. I've had to set JAVA_HOME for it to work. 
cc. @thescouser89

**Comment by thescouser89** [comment]
@michalovjan Ack! Will take a note to set this up in Jenkins

**Comment by thescouser89** [comment]
retest this please

**Comment by thescouser89** [comment]
woop woop! @michalovjan  you should be unlocked now! Apologies for the delay!

**Comment by thescouser89** [comment]
Please don't merge it until we get the right Openshfit image ready. Apologies for delay again on this

**Comment by michalovjan** [comment]
Thx @thescouser89!

**Pull request merged**
