### PR TITLE
NCL-2415: removed improper stream closing

### PR DESCRIPTION
**Pull request by michalszynkiewicz**

### CODE REVIEW

**Comment by michalszynkiewicz** [comment]
The stream from ImportFile is closed when it's passed to and consumed by InputStreamEntity, here: https://gist.github.com/michalszynkiewicz/cc2bd6cac940f867747438f874e6e140#file-inputstreamentity-java-L151

**Comment by janinko** [comment]
add to whitelist

**Comment by michalszynkiewicz** [comment]
restest this please

**Comment by janinko** [comment]
restest this please

**Pull request merged**
