### PR TITLE
move implementation out of rest module

### PR DESCRIPTION
**Pull request by psakar**
add interface for REST api to allow use proxies
fix mapping to json for imported build
initial implementation of rest client to PNC

### CODE REVIEW

**Comment by psakar** [comment]
depends on https://github.com/Commonjava/web-commons-bom/pull/7

**Comment by jdcasey** [comment]
retest this please

**Comment by jdcasey** [comment]
@psakar Can we turn off the integration tests that require a PNC instance to get CI back up and running? Ideally, we can find a way to piggy-back on the work PNC is doing to get ready for OSE, and setup a test environment in which these tests can succeed...but until then we need these tests pushed into a maven profile.

**Comment by jdcasey** [comment]
@psakar Also, I wanted to point out that I've started some work on the various kinds of model classes we'll need to handle talking to Koji/Brew. That stuff is in kojiji (https://github.com/release-engineering/kojiji)

**Comment by jdcasey** [comment]
retest this please

**Pull request merged**
