### PR TITLE
Add metric to track number and size of files when importing builds in…

### PR DESCRIPTION
**Pull request by vibe13**
…to Brew; use of pncmetrics

### Checklist:

* [ ] Have you added a note in the CHANGELOG.md for your change if user-facing?
* [ ] Have you added unit tests for your change?

### CODE REVIEW

**Comment by vibe13** [comment]
@thescouser89 @janinko Ok I am getting compilation errors mainly in PncClientImpl...I believe because all the pieces are in still flux? How shall I proceed? Thanks!

**Comment by thescouser89** [comment]
Ah that's because we changed ints to strings for the ids in our DTOs! I hope it's not too much work to fix those compilations errors @vibe13 ! In theory it should only be changing 'int' or 'Integer' to String.

**Comment by vibe13** [comment]
@thescouser89 is uses 2.0.0-SNAPSHOTversion of org.jboss.pnc:dto. I see also lots of deprecated code, and I could spot (may overlook) only the import of builds, not of milestones. So not sure what to do now :-)

**Comment by thescouser89** [comment]
Aye I'd say merge it if Honza is ok with it. The DTO potential issues are not related to the changes you are introducing :)

**Comment by vibe13** [comment]
@thescouser89 @jbartece  So basically what needs to be replaced in org.jboss.pnc.causeway.rest.model.* with org.jboss.pnc.dto.* ? Is that what needs to be done? Thanks!

**Comment by vibe13** [comment]
> Aye I'd say merge it if Honza is ok with it. The DTO potential issues are not related to the changes you are introducing :)

Sorry did not spot the above and I replied again :-(.  Ok I will merge it as dto replacement is another matter, will talk to @janinko when he is back to try to help there. Thanks!

**Pull request merged**
